name: CI Pipeline


on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust Node.js version as needed

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build the project
        run: npm run build

      # Run tests and generate coverage report
      - name: Run tests and generate coverage
        run: |
          npm run test -- --coverage --reporters=lcov --outputFile=coverage/lcov-report/index.html

      # Publish code coverage
      - name: Upload code coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov-report/index.html
